### PR TITLE
Refactor to allow logfile to work properly

### PR DESCRIPTION
**Pull request by adamcrews**
This is a simple refactor of the logfile define that so that it adheres to the style guide.

### CODE REVIEW

**Comment by mostlyjason** [comment]
Adam sorry its taken so long to review this. We merged several PRs but yours has a version conflict. Do you think you can address the conflict and resubmit?

**Comment by adamcrews** [comment]
No worries, I'll rebase and get things all fixed up.

**Comment by mostlyjason** [comment]
@adamcrews any estimate on when you might get a chance to clean it up? if it's going to be a while we might be able to help

**Comment by adamcrews** [comment]
@mostlyjason I've rebased. It looks good to me to merge, but I have only very briefly tested it.

**Pull request merged**
