### PR TITLE
add loggly::uninstall define, fix syslog-ng include, fix and add beak…

### PR DESCRIPTION
**Pull request by drewrothstein**
This adds a `loggly::uninstall` defined resource type that can be used if a user chooses to remove loggly from their system(s).

This fixes the beaker acceptance tests which were not functional.

This adds working tests for default, rsyslog, and syslog_ng class instantiations.  The CentOS 7 and Debian 7 nodesets were invalid and have been fixed.

This fixes `syslog_ng` on CentOS and RedHat where modern versions _were_ including an `@include` directive preventing `syslog-ng` from starting.  A `match` and `replace` were added to the `file_line` to prevent addition if already present.

This bumps the `stdlib` requirement to `4.12.0` and adds a `git` ignore for all `.DS_Store` files.  The `stdlib` bump is to be able to use `is_absolute_path()`.

Reasonable tests were added and run:

```
Total resources:   24
Touched resources: 22
Resource coverage: 91.67%
```

Acceptance tests were run across a variety of nodesets.

Default (Ubuntu 12.04):

```
Destroying vagrant boxes
==> ubuntu-server-1204-x64: Forcing shutdown of VM...
==> ubuntu-server-1204-x64: Destroying VM and associated drives...

Finished in 30.89 seconds (files took 2 minutes 26.2 seconds to load)
28 examples, 0 failures

Finished in 30.89 seconds (files took 2 minutes 26.2 seconds to load)
28 examples, 0 failures
```

CentOS 7:

```
==> centos-7-x64: Forcing shutdown of VM...
==> centos-7-x64: Destroying VM and associated drives...

Finished in 1 minute 9.08 seconds (files took 4 minutes 25.6 seconds to load)
28 examples, 0 failures

Finished in 1 minute 9.08 seconds (files took 4 minutes 25.6 seconds to load)
28 examples, 0 failures
```

Debian 7:

```
==> debian-711-x64: Forcing shutdown of VM...
==> debian-711-x64: Destroying VM and associated drives...

Finished in 32.1 seconds (files took 4 minutes 23.1 seconds to load)
28 examples, 0 failures

Finished in 32.1 seconds (files took 4 minutes 23.1 seconds to load)
28 examples, 0 failure
```
## 

Real-life testing on an Ubuntu 14.04 VM w/Puppet 4.5.3.

Manifest:

```
loggly::uninstall { 'remove': }
```

Run:

```
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppet
Info: Applying configuration version '1471119053'
Notice: /Stage[main]/Base/Loggly::Uninstall[remove]/File[/usr/local/loggly]/ensure: removed
Info: Computing checksum on file /etc/rsyslog.d/22-loggly.conf
Info: /Stage[main]/Base/Loggly::Uninstall[remove]/File[/etc/rsyslog.d/22-loggly.conf]: Filebucketed /etc/rsyslog.d/22-loggly.conf to puppet with sum b4469457836b11c189b4f5b3658bf898
Notice: /Stage[main]/Base/Loggly::Uninstall[remove]/File[/etc/rsyslog.d/22-loggly.conf]/ensure: removed
Info: /Stage[main]/Base/Loggly::Uninstall[remove]/File[/etc/rsyslog.d/22-loggly.conf]: Scheduling refresh of Exec[restart_rsyslogd]
Notice: /Stage[main]/Base/Loggly::Uninstall[remove]/Exec[restart_rsyslogd]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 0.39 seconds
```

Please let me know if anything further would be required to accept this PR.

Thank you.

### CODE REVIEW

**Comment by mostlyjason** [comment]
@psquickitjayant @mchaudhary is this okay to merge?

**Comment by davidbernick** [comment]
+1 has this been merged or is there a better way to uninstall loggly via puppet?

**Comment by mostlyjason** [comment]
It hasn't been merged. It appears this one is from a long time ago. Seems like we just haven't had a chance to test it yet. Maybe if you can test it we can merge it?

**Comment by drewrothstein** [comment]
Closing my PRs that haven't received any love in a long while.

**Pull request closed without merging**
